# Production override for docker-compose.yml
# This file removes development-specific configurations and optimizes for production

services:
  # Disable adminer in production
  adminer:
    profiles: ["never"] # This prevents the service from starting

  web-dashboard:
    # Remove development volumes - use baked-in code from the image
    volumes: []

    # Remove development-specific working directory override
    # Let the Dockerfile handle the working directory

    # Production-specific environment variables
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Add any production-specific env vars here
      # - NEXT_PUBLIC_API_URL=https://api.yourdomain.com
      # - NEXT_PUBLIC_WS_URL=wss://ws.yourdomain.com

    # Production health check
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3001/api/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

    # Production restart policy
    restart: unless-stopped

    # Remove development-specific port binding if using reverse proxy
    # ports:
    #   - "127.0.0.1:3001:3001"

    # Production resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"
