# HTTP-only override for docker-compose.yml
# This file enables direct IPv4 access with HTTP (no HTTPS/TLS)
# Use this bypass Let's Encrypt rate limiting: docker-compose -f docker-compose.yml -f docker-compose.http.yml up

services:
  # Disable Traefik entirely to allow direct service access
  traefik:
    profiles: ["never"] # This prevents Traefik from starting

  postgres:
    ports:
      - "5432:5432" # External access for debugging (optional - you may want to keep this restricted)
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust # Allow connections without specific password for external access

  adminer:
    ports:
      - "8080:8080" # External admin database access
    profiles: [] # Remove traefik labels to enable direct access

  redis:
    ports:
      - "6379:6379" # External Redis access for debugging

  backend:
    ports:
      - "3000:3000" # External API access via droplet IP
    labels: [] # Remove Traefik labels
    environment:
      - TRUST_PROXY=true # Allow requests from external sources

  filter-processor:
    ports:
      - "8082:8082" # External filter processor access
    labels: [] # Remove Traefik labels

  websocket:
    ports:
      - "8081:8081" # External WebSocket access
    labels: [] # Remove Traefik labels
    environment:
      - TRUST_PROXY=true # Allow WebSocket connections from external sources

  web-dashboard:
    ports:
      - "3001:3001" # External web dashboard access
    labels: [] # Remove Traefik labels
    environment:
      - NODE_ENV=development # Ensure dev mode for better debugging
