import { StyleSheet } from "react-native";
import { COLORS } from "../../Layout/ScreenLayout";

export const legacyStyles = StyleSheet.create({
  // Image-related styles
  imageWrapper: {
    position: "relative",
    width: "100%",
  },
  imageContainer: {
    width: "100%",
    height: 240,
    backgroundColor: COLORS.cardBackground,
    overflow: "hidden",
  },
  eventImage: {
    width: "100%",
    height: "100%",
  },
  placeholderImage: {
    backgroundColor: COLORS.cardBackground,
    justifyContent: "center",
    alignItems: "center",
  },
  placeholderText: {
    color: COLORS.textPrimary,
    fontSize: 16,
    opacity: 0.6,
    fontFamily: "SpaceMono",
  },
  emojiWrapper: {
    position: "absolute",
    top: 20,
    left: 20,
    zIndex: 10,
  },
  emojiContainer: {
    width: 48,
    height: 48,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  emoji: {
    fontSize: 24,
  },
  titleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
    paddingRight: 72,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
    position: "relative",
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: COLORS.textPrimary,
    flex: 1,
    fontFamily: "SpaceMono",
    lineHeight: 32,
  },
  detailsContainer: {
    padding: 20,
  },
  iconContainer: {
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  locationContainer: {
    flex: 1,
  },
  descriptionContainer: {
    flex: 1,
    marginLeft: 0,
  },
  descriptionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 12,
    fontFamily: "SpaceMono",
    flexDirection: "row",
    alignItems: "center",
  },
  viewOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  viewText: {
    color: "#ffffff",
    fontFamily: "SpaceMono",
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 8,
  },
  categoriesSection: {
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  categoriesHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  categoriesTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginLeft: 8,
    fontFamily: "SpaceMono",
    letterSpacing: 0.3,
  },
  discoveredBySection: {
    marginHorizontal: 20,
    marginTop: 20,
    backgroundColor: COLORS.textPrimary,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    overflow: "hidden",
  },
  discoveredByHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
  },
  discoveredByIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(147, 197, 253, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
    borderWidth: 1,
    borderColor: "rgba(147, 197, 253, 0.3)",
  },
  discoveredByTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.textSecondary,
    fontFamily: "SpaceMono",
    letterSpacing: 0.5,
  },

  // Map preview styles
  mapPreview: {
    width: "100%",
    height: "100%",
    borderRadius: 12,
    overflow: "hidden",
  },
  mapPreviewContainer: {
    width: "100%",
    height: 200,
    backgroundColor: COLORS.cardBackground,
    overflow: "hidden",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  mapPreviewFooter: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
    flexDirection: "row",
    justifyContent: "center",
  },
  mapCardFooter: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
  },
  markerContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#ffffff",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: COLORS.accent,
    zIndex: 1000,
  },
  markerEmoji: {
    fontSize: 24,
  },

  // Private event styles
  privateEventImageOverlay: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 100,
    height: 100,
    borderRadius: 12,
    backgroundColor: COLORS.background,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  privateEventImage: {
    width: "100%",
    height: "100%",
  },
  privateEventImageError: {
    color: COLORS.textPrimary,
    fontSize: 12,
    textAlign: "center",
    padding: 8,
  },
  recurringDetailsContainer: {
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: COLORS.background,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  recurringDetailsContent: {
    flex: 1,
    marginLeft: 12,
  },
});
