import { StyleSheet } from "react-native";
import {
  colors,
  spacing,
  radius,
  fontSize,
  fontWeight,
  fontFamily,
  lineHeight,
} from "@/theme";

export const legacyStyles = StyleSheet.create({
  // Image-related styles
  imageWrapper: {
    position: "relative",
    width: "100%",
  },
  imageContainer: {
    width: "100%",
    height: 240,
    backgroundColor: colors.bg.card,
    overflow: "hidden",
  },
  eventImage: {
    width: "100%",
    height: "100%",
  },
  placeholderImage: {
    backgroundColor: colors.bg.card,
    justifyContent: "center",
    alignItems: "center",
  },
  placeholderText: {
    color: colors.text.primary,
    fontSize: fontSize.md,
    opacity: 0.6,
    fontFamily: fontFamily.mono,
  },
  emojiWrapper: {
    position: "absolute",
    top: spacing.xl,
    left: spacing.xl,
    zIndex: 10,
  },
  emojiContainer: {
    width: 48,
    height: 48,
    backgroundColor: colors.overlay.scrim,
    borderRadius: radius.lg,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border.accent,
    shadowColor: colors.fixed.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  emoji: {
    fontSize: fontSize["2xl"],
  },
  titleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: spacing.xl,
    paddingTop: spacing["2xl"],
    paddingBottom: spacing.xl,
    paddingRight: 72,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.default,
    position: "relative",
  },
  title: {
    fontSize: fontSize["2xl"],
    fontWeight: fontWeight.bold,
    color: colors.text.primary,
    flex: 1,
    fontFamily: fontFamily.mono,
    lineHeight: lineHeight.heading,
  },
  detailsContainer: {
    padding: spacing.xl,
  },
  iconContainer: {
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: spacing.sm,
  },
  locationContainer: {
    flex: 1,
  },
  descriptionContainer: {
    flex: 1,
    marginLeft: 0,
  },
  descriptionTitle: {
    fontSize: fontSize.md,
    fontWeight: fontWeight.semibold,
    color: colors.text.primary,
    marginBottom: spacing.md,
    fontFamily: fontFamily.mono,
    flexDirection: "row",
    alignItems: "center",
  },
  viewOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.overlay.medium,
    paddingVertical: spacing.md,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  viewText: {
    color: colors.fixed.white,
    fontFamily: fontFamily.mono,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    marginLeft: spacing.sm,
  },
  categoriesSection: {
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.lg,
  },
  categoriesHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: spacing.lg,
  },
  categoriesTitle: {
    fontSize: fontSize.md,
    fontWeight: fontWeight.semibold,
    color: colors.text.primary,
    marginLeft: spacing.sm,
    fontFamily: fontFamily.mono,
    letterSpacing: 0.3,
  },
  discoveredBySection: {
    marginHorizontal: spacing.xl,
    marginTop: spacing.xl,
    backgroundColor: colors.text.primary,
    borderRadius: radius["2xl"],
    borderWidth: 1,
    borderColor: colors.border.medium,
    overflow: "hidden",
  },
  discoveredByHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.medium,
  },
  discoveredByIconContainer: {
    width: 40,
    height: 40,
    borderRadius: radius.md,
    backgroundColor: colors.accent.muted,
    justifyContent: "center",
    alignItems: "center",
    marginRight: spacing.lg,
    borderWidth: 1,
    borderColor: colors.accent.border,
  },
  discoveredByTitle: {
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    color: colors.text.secondary,
    fontFamily: fontFamily.mono,
    letterSpacing: 0.5,
  },

  // Map preview styles
  mapPreview: {
    width: "100%",
    height: "100%",
    borderRadius: radius.md,
    overflow: "hidden",
  },
  mapPreviewContainer: {
    width: "100%",
    height: 200,
    backgroundColor: colors.bg.card,
    overflow: "hidden",
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  mapPreviewFooter: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.overlay.white,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border.default,
    flexDirection: "row",
    justifyContent: "center",
  },
  mapCardFooter: {
    marginTop: spacing.lg,
    paddingTop: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.border.default,
  },
  markerContainer: {
    width: 40,
    height: 40,
    borderRadius: radius["2xl"],
    backgroundColor: colors.fixed.white,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: colors.accent.primary,
    zIndex: 1000,
  },
  markerEmoji: {
    fontSize: fontSize["2xl"],
  },

  // Private event styles
  privateEventImageOverlay: {
    position: "absolute",
    top: spacing.md,
    right: spacing.md,
    width: 100,
    height: 100,
    borderRadius: radius.md,
    backgroundColor: colors.bg.primary,
    shadowColor: colors.fixed.black,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  privateEventImage: {
    width: "100%",
    height: "100%",
  },
  privateEventImageError: {
    color: colors.text.primary,
    fontSize: fontSize.xs,
    textAlign: "center",
    padding: spacing.sm,
  },
  recurringDetailsContainer: {
    marginTop: spacing.sm,
    marginBottom: spacing.sm,
    backgroundColor: colors.bg.primary,
    borderRadius: radius.md,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  recurringDetailsContent: {
    flex: 1,
    marginLeft: spacing.md,
  },
});
