import { StyleSheet } from "react-native";
import {
  colors,
  spacing,
  radius,
  fontSize,
  fontWeight,
  fontFamily,
  lineHeight,
} from "@/theme";

export const qrCodeStyles = StyleSheet.create({
  qrContent: {
    alignItems: "center",
    gap: spacing.lg,
  },
  qrCodeWrapper: {
    padding: spacing.xl,
    backgroundColor: colors.fixed.white,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border.default,
    shadowColor: colors.fixed.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  qrUrlContainer: {
    width: "100%",
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    backgroundColor: colors.bg.primary,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border.default,
  },
  qrUrlLabel: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.semibold,
    color: colors.accent.primary,
    fontFamily: fontFamily.mono,
    marginBottom: spacing.xs,
    letterSpacing: 0.5,
  },
  qrUrlText: {
    fontSize: fontSize.sm,
    color: colors.text.primary,
    fontFamily: fontFamily.mono,
    lineHeight: lineHeight.tight,
  },
  qrDescription: {
    color: colors.text.secondary,
    fontSize: fontSize.sm,
    fontFamily: fontFamily.mono,
    textAlign: "center",
    lineHeight: lineHeight.normal,
  },
  qrSection: {
    marginHorizontal: spacing.xl,
    marginTop: spacing.xl,
    backgroundColor: "rgba(0, 0, 0, 0.25)",
    borderRadius: radius["2xl"],
    borderWidth: 1,
    borderColor: colors.border.medium,
    overflow: "hidden",
  },
  qrHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.xl,
    paddingVertical: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: colors.border.medium,
  },
  qrIconContainer: {
    width: 40,
    height: 40,
    borderRadius: radius.md,
    backgroundColor: colors.accent.muted,
    justifyContent: "center",
    alignItems: "center",
    marginRight: spacing.lg,
    borderWidth: 1,
    borderColor: colors.accent.border,
  },
  qrTitle: {
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    color: colors.text.primary,
    fontFamily: fontFamily.mono,
    flex: 1,
    letterSpacing: 0.5,
  },
  qrButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: colors.accent.muted,
    paddingVertical: spacing._14,
    paddingHorizontal: spacing["2xl"],
    borderRadius: radius.lg,
    borderWidth: 1,
    borderColor: colors.accent.border,
  },
  qrButtonText: {
    color: colors.accent.primary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    fontFamily: fontFamily.mono,
    marginLeft: spacing._10,
    letterSpacing: 0.5,
  },
});
