import { StyleSheet } from "react-native";

export const filterStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#333",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#3a3a3a",
    backgroundColor: "#333",
    zIndex: 10,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
  },
  addButton: {
    padding: 8,
  },
  contentArea: {
    flex: 1,
    paddingTop: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    fontSize: 16,
    marginTop: 12,
  },
  errorContainer: {
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  errorText: {
    color: "#f97583",
    fontFamily: "SpaceMono",
    fontSize: 14,
    marginBottom: 16,
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: "#93c5fd",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  retryButtonText: {
    color: "#333",
    fontFamily: "SpaceMono",
    fontWeight: "500",
  },
  noResults: {
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  noResultsText: {
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    fontSize: 18,
    fontWeight: "600",
    textAlign: "center",
    marginBottom: 12,
  },
  noResultsSubtext: {
    color: "#adb5bd",
    fontFamily: "SpaceMono",
    fontSize: 14,
    textAlign: "center",
    marginBottom: 24,
    paddingHorizontal: 20,
  },
  createFilterButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#93c5fd",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 8,
  },
  createFilterText: {
    color: "#333",
    fontFamily: "SpaceMono",
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  listContent: {
    padding: 16,
    paddingBottom: 100, // Extra padding for bottom button
  },
  filterCard: {
    backgroundColor: "#3a3a3a",
    borderRadius: 10,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  filterHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#424242",
  },
  filterIconTitle: {
    flexDirection: "row",
    alignItems: "center",
  },
  filterName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    marginLeft: 12,
  },
  activeBadge: {
    backgroundColor: "#40c057",
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  activeText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "500",
    fontFamily: "SpaceMono",
  },
  filterDetails: {
    padding: 16,
    backgroundColor: "#424242",
    borderBottomWidth: 1,
    borderBottomColor: "#505050",
  },
  criteriaSection: {
    marginBottom: 12,
  },
  criteriaLabel: {
    fontSize: 14,
    color: "#93c5fd",
    fontFamily: "SpaceMono",
    fontWeight: "500",
    marginBottom: 4,
  },
  criteriaValue: {
    fontSize: 14,
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
  },
  tagsContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 4,
  },
  tagBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#505050",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  tagText: {
    fontSize: 12,
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    marginRight: 4,
  },
  filterActions: {
    flexDirection: "row",
    justifyContent: "space-around",
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "#424242",
  },
  actionText: {
    color: "#93c5fd",
    fontSize: 14,
    fontFamily: "SpaceMono",
    marginLeft: 8,
  },
  bottomButtonContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    backgroundColor: "#333",
    borderTopWidth: 1,
    borderTopColor: "#3a3a3a",
  },
  clearButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#424242",
    paddingVertical: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#f97583",
  },
  clearButtonText: {
    color: "#f97583",
    fontSize: 16,
    fontWeight: "500",
    fontFamily: "SpaceMono",
    marginLeft: 8,
  },

  // Modal styles
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  modalContent: {
    backgroundColor: "#3a3a3a",
    borderRadius: 10,
    width: "100%",
    maxHeight: "90%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#424242",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
  },
  closeButton: {
    padding: 4,
  },
  modalScrollContent: {
    padding: 16,
  },
  modalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#424242",
  },

  // Form styles
  formGroup: {
    marginBottom: 20,
  },
  formLabel: {
    fontSize: 14,
    color: "#93c5fd",
    fontFamily: "SpaceMono",
    fontWeight: "500",
    marginBottom: 8,
  },
  input: {
    backgroundColor: "#424242",
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    fontSize: 14,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#505050",
  },
  switchContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  categoriesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 4,
  },
  categoryOption: {
    backgroundColor: "#424242",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#505050",
  },
  categorySelected: {
    backgroundColor: "#93c5fd",
    borderColor: "#93c5fd",
  },
  categoryOptionText: {
    color: "#f8f9fa",
    fontSize: 12,
    fontFamily: "SpaceMono",
  },
  categorySelectedText: {
    color: "#333",
    fontWeight: "600",
  },
  dateInputContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  dateInput: {
    flex: 1,
    marginRight: 8,
  },
  dateLabel: {
    fontSize: 12,
    color: "#adb5bd",
    fontFamily: "SpaceMono",
    marginBottom: 4,
  },
  statusOptions: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 4,
  },
  statusOption: {
    backgroundColor: "#424242",
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginRight: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#505050",
  },
  statusSelected: {
    backgroundColor: "#93c5fd",
    borderColor: "#93c5fd",
  },
  statusOptionText: {
    color: "#f8f9fa",
    fontSize: 12,
    fontFamily: "SpaceMono",
  },
  statusSelectedText: {
    color: "#333",
    fontWeight: "600",
  },
  keywordInputContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  keywordInput: {
    flex: 1,
    backgroundColor: "#424242",
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    fontSize: 14,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#505050",
    marginRight: 8,
  },
  addKeywordButton: {
    backgroundColor: "#93c5fd",
    width: 44,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
  },
  cancelButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#adb5bd",
  },
  cancelButtonText: {
    color: "#adb5bd",
    fontSize: 14,
    fontFamily: "SpaceMono",
  },
  saveButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#93c5fd",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  saveButtonText: {
    color: "#333",
    fontSize: 14,
    fontWeight: "600",
    fontFamily: "SpaceMono",
    marginLeft: 8,
  },
});
