import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#333",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#3a3a3a",
    backgroundColor: "#333",
    zIndex: 10,
  },
  backButton: {
    padding: 8,
    marginRight: 12,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    flex: 1,
  },
  editButton: {
    padding: 8,
  },
  contentArea: {
    flex: 1,
    paddingTop: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    fontSize: 16,
    marginTop: 12,
  },
  errorContainer: {
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  errorText: {
    color: "#f97583",
    fontFamily: "SpaceMono",
    fontSize: 14,
    marginBottom: 16,
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: "#93c5fd",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  retryButtonText: {
    color: "#333",
    fontFamily: "SpaceMono",
    fontWeight: "500",
  },
  noResults: {
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  noResultsText: {
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    fontSize: 16,
    textAlign: "center",
  },
  userContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  userHeaderContainer: {
    flexDirection: "row",
    backgroundColor: "#3a3a3a",
    borderRadius: 10,
    padding: 16,
    marginVertical: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    alignItems: "center",
  },
  userTitleWrapper: {
    flex: 1,
  },
  avatarContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: "#93c5fd",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
  },
  avatarText: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#333",
    fontFamily: "SpaceMono",
  },
  resultTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
  },
  statusBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#40c057",
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginTop: 6,
  },
  statusText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "500",
    fontFamily: "SpaceMono",
  },
  detailsContainer: {
    backgroundColor: "#3a3a3a",
    borderRadius: 10,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  detailSection: {
    marginBottom: 20,
  },
  resultDetailsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  detailLabel: {
    fontSize: 14,
    color: "#93c5fd",
    fontFamily: "SpaceMono",
    fontWeight: "500",
  },
  detailValue: {
    fontSize: 15,
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    marginLeft: 24, // Aligns with the icon in the row above
    marginTop: 2,
  },
  inputField: {
    backgroundColor: "#444",
    borderRadius: 6,
    padding: 10,
    marginLeft: 24,
    marginTop: 2,
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    fontSize: 15,
  },
  bioInput: {
    height: 100,
    textAlignVertical: "top",
  },
  statSection: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: 10,
    marginBottom: 20,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#444",
  },
  statItem: {
    alignItems: "center",
  },
  statValue: {
    color: "#93c5fd",
    fontFamily: "SpaceMono",
    fontSize: 18,
    fontWeight: "bold",
  },
  statLabel: {
    color: "#adb5bd",
    fontFamily: "SpaceMono",
    fontSize: 12,
    marginTop: 4,
  },
  actionButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 10,
  },
  actionButton: {
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  saveButton: {
    backgroundColor: "#40c057",
    flex: 3,
    marginLeft: 8,
  },
  saveButtonText: {
    color: "#fff",
    fontFamily: "SpaceMono",
    fontWeight: "600",
    fontSize: 14,
  },
  cancelButton: {
    backgroundColor: "#3a3a3a",
    borderWidth: 1,
    borderColor: "#adb5bd",
    flex: 2,
  },
  cancelButtonText: {
    color: "#adb5bd",
    fontFamily: "SpaceMono",
    fontWeight: "500",
    fontSize: 14,
  },
});
