// styles/share.tsx
import { StyleSheet } from "react-native";

export const share = StyleSheet.create({
  // Share preview styles
  sharePreview: {
    backgroundColor: "#3a3a3a",
    borderRadius: 12,
    padding: 16,
    margin: 16,
    marginTop: 24,
  },
  shareEventTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#f8f9fa",
    marginBottom: 8,
    fontFamily: "SpaceMono",
  },
  shareEventDetails: {
    fontSize: 14,
    color: "#cbd5e1",
    fontFamily: "SpaceMono",
  },
  shareTextContainer: {
    backgroundColor: "#374151",
    borderRadius: 12,
    padding: 12,
    marginHorizontal: 16,
    marginBottom: 16,
  },
  shareTextInput: {
    color: "#f8f9fa",
    fontSize: 14,
    fontFamily: "SpaceMono",
    minHeight: 80,
    textAlignVertical: "top",
  },
  shareViaText: {
    fontSize: 16,
    fontWeight: "500",
    color: "#fcd34d",
    marginHorizontal: 16,
    marginBottom: 12,
    fontFamily: "SpaceMono",
  },
  shareOptionsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    paddingHorizontal: 8,
    marginBottom: 24,
  },
  shareOption: {
    width: "33%",
    alignItems: "center",
    marginBottom: 16,
  },
  shareOptionIconContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#374151",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 8,
  },
  shareOptionText: {
    fontSize: 12,
    color: "#cbd5e1",
    textAlign: "center",
    fontFamily: "SpaceMono",
  },
  copiedText: {
    fontSize: 10,
    color: "#4ade80",
    marginTop: 4,
    fontFamily: "SpaceMono",
  },
  shareButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#4dabf7",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 24,
    marginHorizontal: 24,
    marginBottom: 24,
  },
  shareButtonIcon: {
    marginRight: 8,
  },
  shareButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#fff",
    fontFamily: "SpaceMono",
  },

  // Contact selector styles
  searchInputContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#3a3a3a",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    margin: 16,
    marginTop: 8,
    borderWidth: 1,
    borderColor: "#4a4a4a",
  },
  searchInput: {
    flex: 1,
    color: "#f8f9fa",
    fontSize: 16,
    fontFamily: "SpaceMono",
    padding: 0,
  },
  selectedContactsPreview: {
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#3a3a3a",
  },
  selectedContactsText: {
    fontSize: 14,
    color: "#fcd34d",
    fontFamily: "SpaceMono",
  },
  contactsList: {
    flex: 1,
  },
  contactsListContent: {
    paddingHorizontal: 16,
    paddingBottom: 16,
  },
  contactItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#3a3a3a",
  },
  contactItemSelected: {
    backgroundColor: "rgba(76, 175, 80, 0.1)",
    borderRadius: 8,
    paddingHorizontal: 8,
  },
  contactAvatarContainer: {
    marginRight: 12,
  },
  contactAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  contactAvatarPlaceholder: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#4dabf7",
    justifyContent: "center",
    alignItems: "center",
  },
  contactAvatarText: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#fff",
    fontFamily: "SpaceMono",
  },
  contactInfo: {
    flex: 1,
  },
  contactName: {
    fontSize: 16,
    fontWeight: "500",
    color: "#f8f9fa",
    marginBottom: 4,
    fontFamily: "SpaceMono",
  },
  contactDetail: {
    fontSize: 12,
    color: "#cbd5e1",
    fontFamily: "SpaceMono",
  },
  contactSelectIndicator: {
    width: 24,
    alignItems: "center",
    justifyContent: "center",
  },
  contactSelectedIcon: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: "#4ade80",
    alignItems: "center",
    justifyContent: "center",
  },
  contactSelectedIconText: {
    fontSize: 12,
    fontWeight: "bold",
    color: "#fff",
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 48,
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
  },
  permissionContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  permissionText: {
    fontSize: 16,
    color: "#f8f9fa",
    textAlign: "center",
    fontFamily: "SpaceMono",
  },
  noResultsContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 24,
  },
  noResultsText: {
    fontSize: 16,
    color: "#f8f9fa",
    textAlign: "center",
    fontFamily: "SpaceMono",
  },
  shareActionButton: {
    backgroundColor: "#4dabf7",
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  shareActionButtonText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#fff",
    fontFamily: "SpaceMono",
  },
});
