import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#333",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#3a3a3a",
    backgroundColor: "#333",
    zIndex: 10,
  },
  backButton: {
    padding: 8,
    marginRight: 12,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    flex: 1,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerActionButton: {
    padding: 8,
    marginLeft: 4,
  },
  contentArea: {
    flex: 1,
    paddingTop: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    fontSize: 16,
    marginTop: 12,
  },
  errorContainer: {
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  errorText: {
    color: "#f97583",
    fontFamily: "SpaceMono",
    fontSize: 14,
    marginBottom: 16,
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: "#93c5fd",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  retryButtonText: {
    color: "#333",
    fontFamily: "SpaceMono",
    fontWeight: "500",
  },
  noResults: {
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  noResultsText: {
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    fontSize: 16,
    textAlign: "center",
  },
  categoriesContainer: {
    flex: 1,
  },
  infoHeaderContainer: {
    flexDirection: "row",
    backgroundColor: "#3a3a3a",
    borderRadius: 10,
    padding: 16,
    marginHorizontal: 16,
    marginVertical: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    alignItems: "center",
  },
  infoHeaderIconContainer: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: "#424242",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
  },
  infoHeaderTextContainer: {
    flex: 1,
  },
  infoHeaderTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
  },
  infoHeaderDescription: {
    fontSize: 14,
    color: "#adb5bd",
    fontFamily: "SpaceMono",
    marginTop: 4,
  },
  categoryListContent: {
    paddingHorizontal: 16,
    paddingBottom: 80, // Extra space for the bottom button
  },
  categoryItem: {
    flexDirection: "row",
    backgroundColor: "#3a3a3a",
    borderRadius: 10,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#3a3a3a",
  },

  categoryEmoji: {
    fontSize: 24,
    marginRight: 14,
  },
  categoryTextContainer: {
    flex: 1,
  },
  categoryName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
  },
  categoryDescription: {
    fontSize: 14,
    color: "#adb5bd",
    fontFamily: "SpaceMono",
    marginTop: 4,
  },
  bottomButtonContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#3a3a3a",
    backgroundColor: "#333",
  },
  createButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#424242",
    paddingVertical: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#93c5fd",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 2,
  },
  createButtonText: {
    color: "#93c5fd",
    fontSize: 16,
    fontWeight: "500",
    fontFamily: "SpaceMono",
  },
  checkboxContainer: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#93c5fd",
    marginLeft: "auto",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "transparent",
  },
  checkboxSelected: {
    backgroundColor: "#93c5fd",
    borderColor: "#93c5fd",
  },
  selectionFooter: {
    backgroundColor: "#1f2937",
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderTopColor: "#374151",
  },
  clearButton: {
    marginLeft: 12,
    paddingVertical: 4,
    paddingHorizontal: 8,
  },
  clearButtonText: {
    color: "#93c5fd",
    fontSize: 14,
    fontWeight: "500",
  },
  selectionFooterLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  selectionCount: {
    color: "#f8f9fa",
    fontSize: 16,
  },
  confirmButton: {
    backgroundColor: "#3b82f6",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
  },
  confirmButtonDisabled: {
    backgroundColor: "#6b7280",
    opacity: 0.7,
  },
  confirmButtonText: {
    color: "#ffffff",
    fontWeight: "600",
    fontSize: 16,
  },
  categoryItemSelected: {
    backgroundColor: "#1e3a8a14", // Light blue background for selected items
    borderColor: "#93c5fd",
  },
});
