import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#333",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#3a3a3a",
    backgroundColor: "#333",
    zIndex: 10,
  },
  backButton: {
    padding: 8,
    marginRight: 12,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "600",
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
  },
  contentArea: {
    flex: 1,
    paddingTop: 8,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    fontSize: 16,
    marginTop: 12,
  },
  errorContainer: {
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  errorText: {
    color: "#f97583",
    fontFamily: "SpaceMono",
    fontSize: 14,
    marginBottom: 16,
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: "#93c5fd",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  retryButtonText: {
    color: "#333",
    fontFamily: "SpaceMono",
    fontWeight: "500",
  },
  noResults: {
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
  },
  noResultsText: {
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    fontSize: 16,
    textAlign: "center",
  },
  eventContainer: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  eventHeaderContainer: {
    flexDirection: "row",
    backgroundColor: "#3a3a3a",
    borderRadius: 10,
    padding: 16,
    marginVertical: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    alignItems: "center",
  },
  eventTitleWrapper: {
    flex: 1,
  },
  resultEmoji: {
    fontSize: 28,
    marginRight: 14,
  },
  resultTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
  },
  statusBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#40c057",
    borderRadius: 4,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginTop: 6,
  },
  statusText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "500",
    fontFamily: "SpaceMono",
  },
  detailsContainer: {
    backgroundColor: "#3a3a3a",
    borderRadius: 10,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  detailSection: {
    marginBottom: 20,
  },
  resultDetailsRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  detailLabel: {
    fontSize: 14,
    color: "#93c5fd",
    fontFamily: "SpaceMono",
    fontWeight: "500",
  },
  detailValue: {
    fontSize: 15,
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
    marginLeft: 24, // Aligns with the icon in the row above
    marginTop: 2,
  },
  distanceText: {
    fontSize: 13,
    color: "#adb5bd",
    fontFamily: "SpaceMono",
    marginLeft: 24,
    marginTop: 4,
  },
  // New style for distance info
  distanceInfoContainer: {
    marginLeft: 24,
    marginTop: 4,
    backgroundColor: "#4a4a4a",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    alignSelf: "flex-start",
  },
  distanceInfoText: {
    fontSize: 13,
    color: "#93c5fd",
    fontFamily: "SpaceMono",
    fontWeight: "500",
  },
  categoriesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 8,
    marginLeft: 24,
  },
  categoryBadge: {
    backgroundColor: "#4a4a4a",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    marginRight: 8,
    marginBottom: 8,
  },
  categoryText: {
    fontSize: 12,
    color: "#f8f9fa",
    fontFamily: "SpaceMono",
  },
  saveButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#424242",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  saveCountContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 4,
    paddingHorizontal: 12,
    marginBottom: 12,
    marginTop: -6,
  },
  saveCountText: {
    color: "#adb5bd",
    fontSize: 13,
    fontFamily: "SpaceMono",
  },
  timezoneText: {
    color: "#93c5fd",
    fontSize: 12,
    fontWeight: "500",
    marginLeft: 24,
    marginTop: 4,
  },
  locationContainer: {
    width: "100%",
  },
  // Container for location action buttons
  locationActionContainer: {
    flexDirection: "row",
    marginLeft: 24,
    marginTop: 10,
    gap: 12,
  },
  // Updated styles for the mapButton
  mapButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#424242",
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#93c5fd",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 2,
  },
  mapButtonText: {
    color: "#93c5fd",
    fontSize: 14,
    fontWeight: "500",
    marginLeft: 8,
    fontFamily: "SpaceMono",
  },
  // New directions button
  directionsButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#424242",
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#93c5fd",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 2,
  },
  directionsButtonText: {
    color: "#93c5fd",
    fontSize: 14,
    fontWeight: "500",
    marginLeft: 8,
    fontFamily: "SpaceMono",
  },
  bottomButtonContainer: {
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: "#3a3a3a",
    backgroundColor: "#333",
  },
  shareButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#424242",
    paddingVertical: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#93c5fd",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
    elevation: 2,
  },
  shareButtonText: {
    color: "#93c5fd",
    fontSize: 16,
    fontWeight: "500",
    fontFamily: "SpaceMono",
  },
});
