import { StyleSheet, Dimensions } from "react-native";
import { COLORS } from "../Layout/ScreenLayout";

const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  contentContainer: {
    paddingBottom: 24,
  },
  headerActions: {
    flexDirection: "row",
    gap: 12,
  },

  // Hero Section
  heroSection: {
    position: "relative",
    width: "100%",
  },
  heroImageContainer: {
    width: "100%",
    height: 280,
    backgroundColor: COLORS.cardBackground,
    overflow: "hidden",
  },
  eventBadgeOverlay: {
    position: "absolute",
    top: 20,
    left: 20,
    zIndex: 10,
  },
  eventBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  eventBadgeText: {
    fontSize: 12,
    fontWeight: "600",
    fontFamily: "SpaceMono",
    letterSpacing: 0.5,
  },
  engagementOverlay: {
    position: "absolute",
    bottom: 20,
    right: 20,
    zIndex: 10,
  },

  // Title Section
  titleSection: {
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 16,
    backgroundColor: COLORS.cardBackground,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
  },
  eventTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: COLORS.textPrimary,
    fontFamily: "SpaceMono",
    lineHeight: 36,
    marginBottom: 12,
  },
  eventEmojiContainer: {
    alignSelf: "flex-start",
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: COLORS.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  eventEmoji: {
    fontSize: 24,
  },

  // Details Section
  detailsSection: {
    paddingHorizontal: 20,
    paddingTop: 20,
    gap: 24,
  },

  // Info Card Components
  infoCard: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: COLORS.divider,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
    overflow: "hidden",
  },
  infoCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
    backgroundColor: COLORS.background,
  },
  infoCardIcon: {
    width: 32,
    height: 32,
    borderRadius: 8,
    backgroundColor: COLORS.cardBackground,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  infoCardTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    fontFamily: "SpaceMono",
  },
  infoCardContent: {
    padding: 20,
  },

  // Detail Rows
  detailRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  detailText: {
    color: COLORS.textPrimary,
    fontSize: 16,
    flex: 1,
    fontFamily: "SpaceMono",
    lineHeight: 24,
  },
  detailTextSecondary: {
    color: COLORS.textSecondary,
    fontSize: 14,
    fontFamily: "SpaceMono",
    lineHeight: 20,
    marginTop: 4,
  },

  // Location Content
  locationContent: {
    flex: 1,
  },
  distanceText: {
    color: COLORS.accent,
    fontSize: 14,
    fontFamily: "SpaceMono",
    marginTop: 4,
    fontWeight: "500",
  },

  // Description
  descriptionText: {
    fontSize: 16,
    color: COLORS.textPrimary,
    lineHeight: 24,
    fontFamily: "SpaceMono",
  },

  // Recurring Details
  recurringDetails: {
    gap: 8,
  },

  // Categories
  categoriesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  categoryTag: {
    backgroundColor: COLORS.accent + "15", // 15% opacity
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: COLORS.accent + "30", // 30% opacity
  },
  categoryText: {
    color: COLORS.accent,
    fontSize: 14,
    fontFamily: "SpaceMono",
    fontWeight: "500",
  },

  // Actions Section
  actionsSection: {
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  actionButtonsContainer: {
    flexDirection: "row",
    gap: 12,
  },
  actionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  actionButtonText: {
    fontSize: 14,
    fontWeight: "600",
    fontFamily: "SpaceMono",
  },

  // Admin Section
  adminSection: {
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.textPrimary,
    fontFamily: "SpaceMono",
    marginBottom: 12,
  },
  adminActionsContainer: {
    flexDirection: "row",
    gap: 12,
  },

  // QR Code Section
  qrContent: {
    alignItems: "center",
    gap: 16,
  },
  qrCodeWrapper: {
    padding: 20,
    backgroundColor: "#ffffff",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.divider,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  qrUrlContainer: {
    width: "100%",
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: COLORS.background,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  qrUrlLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: COLORS.accent,
    fontFamily: "SpaceMono",
    marginBottom: 4,
    letterSpacing: 0.5,
  },
  qrUrlText: {
    fontSize: 14,
    color: COLORS.textPrimary,
    fontFamily: "SpaceMono",
    lineHeight: 18,
  },
  qrDescription: {
    color: COLORS.textSecondary,
    fontSize: 14,
    fontFamily: "SpaceMono",
    textAlign: "center",
    lineHeight: 20,
  },

  // Discovered By Section
  discoveredByContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  discoveredByText: {
    fontSize: 16,
    color: COLORS.textPrimary,
    fontFamily: "SpaceMono",
  },
  discoveredByName: {
    fontWeight: "600",
    color: COLORS.accent,
  },

  // Modal Styles
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.95)",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "flex-end",
    padding: 16,
    paddingTop: 50,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 10,
  },
  closeButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  modalContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  fullImage: {
    width: windowWidth,
    height: windowHeight * 0.7,
  },

  // Dialog Styles
  dialogOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  dialogContainer: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 16,
    padding: 24,
    width: "85%",
    maxWidth: 400,
    borderWidth: 1,
    borderColor: COLORS.divider,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 10,
  },
  dialogTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: COLORS.textPrimary,
    marginBottom: 12,
    fontFamily: "SpaceMono",
  },
  dialogText: {
    fontSize: 16,
    color: COLORS.textSecondary,
    marginBottom: 24,
    fontFamily: "SpaceMono",
    lineHeight: 22,
  },
  dialogButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
  },
  dialogButton: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    minWidth: 80,
    alignItems: "center",
  },
  dialogButtonCancel: {
    backgroundColor: COLORS.background,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  dialogButtonDelete: {
    backgroundColor: COLORS.errorBackground,
  },
  dialogButtonTextCancel: {
    fontSize: 14,
    fontWeight: "600",
    fontFamily: "SpaceMono",
    color: COLORS.textPrimary,
  },
  dialogButtonTextDelete: {
    fontSize: 14,
    fontWeight: "600",
    fontFamily: "SpaceMono",
    color: "#ffffff",
  },

  // Legacy styles for compatibility
  loadingContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: COLORS.textSecondary,
    marginTop: 16,
    fontSize: 16,
    fontFamily: "SpaceMono",
  },
  shareIconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: COLORS.cardBackground,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  imageWrapper: {
    position: "relative",
    width: "100%",
  },
  imageContainer: {
    width: "100%",
    height: 240,
    backgroundColor: COLORS.cardBackground,
    overflow: "hidden",
  },
  eventImage: {
    width: "100%",
    height: "100%",
  },
  placeholderImage: {
    backgroundColor: COLORS.cardBackground,
    justifyContent: "center",
    alignItems: "center",
  },
  placeholderText: {
    color: COLORS.textPrimary,
    fontSize: 16,
    opacity: 0.6,
    fontFamily: "SpaceMono",
  },
  emojiWrapper: {
    position: "absolute",
    top: 20,
    left: 20,
    zIndex: 10,
  },
  emojiContainer: {
    width: 48,
    height: 48,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  emoji: {
    fontSize: 24,
  },
  titleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
    paddingRight: 72,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
    position: "relative",
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: COLORS.textPrimary,
    flex: 1,
    fontFamily: "SpaceMono",
    lineHeight: 32,
  },
  saveButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: COLORS.cardBackground,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  savedButton: {
    backgroundColor: COLORS.accent,
    borderColor: "transparent",
  },
  saveButtonText: {
    color: COLORS.textPrimary,
    fontSize: 14,
    fontWeight: "500",
    fontFamily: "SpaceMono",
  },
  savedButtonText: {
    color: COLORS.background,
  },
  detailsContainer: {
    padding: 20,
  },
  iconContainer: {
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  locationContainer: {
    flex: 1,
  },
  descriptionContainer: {
    flex: 1,
    marginLeft: 0,
  },
  descriptionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 12,
    fontFamily: "SpaceMono",
    flexDirection: "row",
    alignItems: "center",
  },
  viewOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  viewText: {
    color: "#ffffff",
    fontFamily: "SpaceMono",
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 8,
  },
  adminButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  adminButtonText: {
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "SpaceMono",
  },
  categoriesSection: {
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  categoriesHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  categoriesTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginLeft: 8,
    fontFamily: "SpaceMono",
    letterSpacing: 0.3,
  },
  qrSection: {
    marginHorizontal: 20,
    marginTop: 20,
    backgroundColor: "rgba(0, 0, 0, 0.25)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    overflow: "hidden",
  },
  qrHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
  },
  qrIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(147, 197, 253, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
    borderWidth: 1,
    borderColor: "rgba(147, 197, 253, 0.3)",
  },
  qrTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.textPrimary,
    fontFamily: "SpaceMono",
    flex: 1,
    letterSpacing: 0.5,
  },
  qrButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(147, 197, 253, 0.15)",
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(147, 197, 253, 0.3)",
  },
  qrButtonText: {
    color: COLORS.accent,
    fontSize: 14,
    fontWeight: "600",
    fontFamily: "SpaceMono",
    marginLeft: 10,
    letterSpacing: 0.5,
  },
  discoveredBySection: {
    marginHorizontal: 20,
    marginTop: 20,
    backgroundColor: COLORS.textPrimary,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    overflow: "hidden",
  },
  discoveredByHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
  },
  discoveredByIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(147, 197, 253, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
    borderWidth: 1,
    borderColor: "rgba(147, 197, 253, 0.3)",
  },
  discoveredByTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.textSecondary,
    fontFamily: "SpaceMono",
    letterSpacing: 0.5,
  },
  mapPreview: {
    width: "100%",
    height: "100%",
    borderRadius: 12,
    overflow: "hidden",
  },
  mapPreviewContainer: {
    width: "100%",
    height: 200,
    backgroundColor: COLORS.cardBackground,
    overflow: "hidden",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  mapPreviewFooter: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
    flexDirection: "row",
    justifyContent: "center",
  },
  directionsButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: COLORS.accent + "10",
    borderWidth: 1,
    borderColor: COLORS.accent + "20",
  },
  directionsButtonDisabled: {
    backgroundColor: COLORS.divider,
    borderColor: COLORS.divider,
  },
  directionsButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.accent,
    fontFamily: "SpaceMono",
  },
  directionsButtonTextDisabled: {
    color: "#9ca3af",
  },
  mapCardFooter: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: COLORS.divider,
  },
  markerContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#ffffff",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: COLORS.accent,
    zIndex: 1000,
  },
  markerEmoji: {
    fontSize: 24,
  },
  privateEventImageOverlay: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 100,
    height: 100,
    borderRadius: 12,
    backgroundColor: COLORS.background,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  privateEventImage: {
    width: "100%",
    height: "100%",
  },
  privateEventImageError: {
    color: COLORS.textPrimary,
    fontSize: 12,
    textAlign: "center",
    padding: 8,
  },
  recurringDetailsContainer: {
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: COLORS.background,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  recurringDetailsContent: {
    flex: 1,
    marginLeft: 12,
  },
});
