import { StyleSheet, Dimensions } from "react-native";
import { COLORS } from "../Layout/ScreenLayout";

const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
    justifyContent: "center",
    alignItems: "center",
  },
  loadingText: {
    color: COLORS.textSecondary,
    marginTop: 16,
    fontSize: 16,
    fontFamily: "SpaceMono",
  },
  contentContainer: {
    paddingBottom: 24,
  },
  shareIconButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: COLORS.cardBackground,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  imageWrapper: {
    position: "relative",
    width: "100%",
  },
  imageContainer: {
    width: "100%",
    height: 240,
    backgroundColor: COLORS.buttonBackground,
    overflow: "hidden",
  },
  eventImage: {
    width: "100%",
    height: "100%",
  },
  placeholderImage: {
    backgroundColor: COLORS.buttonBackground,
    justifyContent: "center",
    alignItems: "center",
  },
  placeholderText: {
    color: COLORS.textPrimary,
    fontSize: 16,
    opacity: 0.6,
    fontFamily: "SpaceMono",
  },
  emojiWrapper: {
    position: "absolute",
    top: 20,
    left: 20,
    zIndex: 10,
  },
  emojiContainer: {
    width: 48,
    height: 48,
    backgroundColor: "rgba(0, 0, 0, 0.75)",
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 5,
  },
  emoji: {
    fontSize: 24,
  },
  titleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 20,
    paddingRight: 72,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.divider,
    position: "relative",
  },
  title: {
    fontSize: 24,
    fontWeight: "700",
    color: COLORS.textPrimary,
    flex: 1,
    fontFamily: "SpaceMono",
    lineHeight: 32,
  },
  saveButton: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: COLORS.cardBackground,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  savedButton: {
    backgroundColor: COLORS.accent,
    borderColor: "transparent",
  },
  saveButtonText: {
    color: COLORS.textPrimary,
    fontSize: 14,
    fontWeight: "500",
    fontFamily: "SpaceMono",
  },
  savedButtonText: {
    color: COLORS.background,
  },
  detailsContainer: {
    padding: 20,
  },
  detailRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 20,
    paddingVertical: 4,
  },
  iconContainer: {
    width: 20,
    height: 20,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 8,
  },
  detailText: {
    color: COLORS.textPrimary,
    fontSize: 16,
    flex: 1,
    fontFamily: "SpaceMono",
    lineHeight: 22,
  },
  detailTextSecondary: {
    color: COLORS.textSecondary,
    fontSize: 14,
    fontFamily: "SpaceMono",
    lineHeight: 20,
    opacity: 0.9,
  },
  locationContainer: {
    flex: 1,
  },
  distanceText: {
    color: COLORS.accent,
    fontSize: 13,
    marginTop: 4,
    fontFamily: "SpaceMono",
    opacity: 0.9,
  },
  descriptionContainer: {
    flex: 1,
    marginLeft: 0,
  },
  descriptionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginBottom: 12,
    fontFamily: "SpaceMono",
    flexDirection: "row",
    alignItems: "center",
  },
  descriptionText: {
    fontSize: 15,
    color: COLORS.textPrimary,
    lineHeight: 24,
    fontFamily: "SpaceMono",
    opacity: 0.9,
  },
  actionButtonsContainer: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8,
  },
  actionButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 12,
    backgroundColor: COLORS.cardBackground,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  actionButtonText: {
    color: COLORS.textPrimary,
    fontSize: 14,
    fontWeight: "500",
    fontFamily: "SpaceMono",
  },
  // Image overlay styles
  viewOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  viewText: {
    color: "#ffffff",
    fontFamily: "SpaceMono",
    fontSize: 14,
    fontWeight: "600",
    marginLeft: 8,
  },
  // Modal styles
  modalContainer: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.95)",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: 16,
    paddingTop: 50,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    zIndex: 10,
  },
  closeButton: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(255, 255, 255, 0.05)",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  adminActionsContainer: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 16,
    marginBottom: 24,
  },
  adminButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  adminButtonText: {
    fontSize: 16,
    fontWeight: "600",
    fontFamily: "SpaceMono",
  },
  modalContent: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  fullImage: {
    width: windowWidth,
    height: windowHeight * 0.7,
  },
  // Categories styles
  categoriesSection: {
    paddingHorizontal: 20,
    paddingVertical: 16,
  },
  categoriesHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  categoriesTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.textPrimary,
    marginLeft: 8,
    fontFamily: "SpaceMono",
    letterSpacing: 0.3,
  },
  categoriesContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginLeft: 28,
  },
  categoryTag: {
    backgroundColor: "rgba(147, 197, 253, 0.1)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "rgba(147, 197, 253, 0.2)",
  },
  categoryText: {
    fontSize: 13,
    color: COLORS.accent,
    fontFamily: "SpaceMono",
    fontWeight: "500",
    letterSpacing: 0.3,
    lineHeight: 18,
  },
  // QR Code section styles
  qrSection: {
    marginHorizontal: 20,
    marginTop: 20,
    backgroundColor: "rgba(0, 0, 0, 0.25)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    overflow: "hidden",
  },
  qrHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
  },
  qrIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(147, 197, 253, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
    borderWidth: 1,
    borderColor: "rgba(147, 197, 253, 0.3)",
  },
  qrTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.textPrimary,
    fontFamily: "SpaceMono",
    flex: 1,
    letterSpacing: 0.5,
  },
  qrContent: {
    padding: 20,
    alignItems: "center",
  },
  qrCodeWrapper: {
    padding: 20,
    backgroundColor: "#ffffff",
    borderRadius: 16,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.44,
    shadowRadius: 10.32,
    elevation: 16,
  },
  qrDescription: {
    color: COLORS.textSecondary,
    fontSize: 14,
    fontFamily: "SpaceMono",
    textAlign: "center",
    marginBottom: 20,
    lineHeight: 20,
    opacity: 0.8,
  },
  qrButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(147, 197, 253, 0.15)",
    paddingVertical: 14,
    paddingHorizontal: 24,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "rgba(147, 197, 253, 0.3)",
  },
  qrButtonText: {
    color: COLORS.accent,
    fontSize: 14,
    fontWeight: "600",
    fontFamily: "SpaceMono",
    marginLeft: 10,
    letterSpacing: 0.5,
  },
  // Discovered By section styles
  discoveredBySection: {
    marginHorizontal: 20,
    marginTop: 20,
    backgroundColor: "rgba(0, 0, 0, 0.25)",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    overflow: "hidden",
  },
  discoveredByHeader: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
  },
  discoveredByIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "rgba(147, 197, 253, 0.15)",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
    borderWidth: 1,
    borderColor: "rgba(147, 197, 253, 0.3)",
  },
  discoveredByTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: COLORS.textSecondary,
    fontFamily: "SpaceMono",
    letterSpacing: 0.5,
  },
  discoveredByName: {
    fontSize: 16,
    color: COLORS.textPrimary,
    fontFamily: "SpaceMono",
    fontWeight: "700",
    letterSpacing: 0.3,
    marginLeft: 6,
  },
  // Dialog modal styles
  dialogOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  dialogContainer: {
    backgroundColor: COLORS.cardBackground,
    borderRadius: 16,
    padding: 24,
    width: "85%",
    maxWidth: 400,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  dialogTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: COLORS.textPrimary,
    marginBottom: 12,
    fontFamily: "SpaceMono",
  },
  dialogText: {
    fontSize: 16,
    color: COLORS.textSecondary,
    marginBottom: 24,
    fontFamily: "SpaceMono",
    lineHeight: 22,
  },
  dialogButtons: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
  },
  dialogButton: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    minWidth: 80,
    alignItems: "center",
  },
  dialogButtonText: {
    fontSize: 14,
    fontWeight: "600",
    fontFamily: "SpaceMono",
  },
  mapPreview: {
    width: "100%",
    height: "100%",
    borderRadius: 0,
    overflow: "visible",
  },
  markerContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#ffffff",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: COLORS.accent,
    zIndex: 1000,
  },
  markerEmoji: {
    fontSize: 24,
  },
  privateEventImageOverlay: {
    position: "absolute",
    top: 12,
    right: 12,
    width: 100,
    height: 100,
    borderRadius: 12,
    backgroundColor: COLORS.background,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  privateEventImage: {
    width: "100%",
    height: "100%",
  },
  privateEventImageError: {
    color: COLORS.textPrimary,
    fontSize: 12,
    textAlign: "center",
    padding: 8,
  },
  recurringDetailsContainer: {
    marginTop: 8,
    marginBottom: 8,
    backgroundColor: COLORS.background,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: COLORS.divider,
  },
  recurringDetailsContent: {
    flex: 1,
    marginLeft: 12,
  },
});
