import { StyleSheet } from "react-native";
import {
  colors,
  spacing,
  radius,
  fontSize,
  fontWeight,
  fontFamily,
} from "@/theme";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.fixed.black,
  },
  map: {
    flex: 1,
  },
  assistantOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: colors.fixed.transparent,
    pointerEvents: "box-none", // Allow touch events to pass through to map
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.overlay.medium,
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  loadingText: {
    color: colors.text.primary,
    fontSize: fontSize.md,
    marginTop: spacing.md,
    fontFamily: fontFamily.mono,
  },
  userLocationMarker: {
    width: spacing.xl,
    height: spacing.xl,
    alignItems: "center",
    justifyContent: "center",
  },
  userLocationDot: {
    width: spacing.lg,
    height: spacing.lg,
    borderRadius: spacing.sm,
    backgroundColor: colors.connection.dot,
    borderWidth: 3,
    borderColor: colors.fixed.white,
  },
  smartNavToggle: {
    position: "absolute",
    top: 80,
    right: spacing.lg,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: radius["2xl"],
    elevation: 3,
    shadowColor: colors.fixed.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  toggleButtonText: {
    color: colors.fixed.white,
    fontWeight: fontWeight.bold,
    fontSize: fontSize.sm,
    marginLeft: spacing._6,
  },
  smartNavContainer: {
    position: "absolute",
    top: 130,
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    paddingHorizontal: spacing.md,
    paddingVertical: spacing._6,
    borderRadius: radius.xl,
    elevation: 2,
    shadowColor: colors.fixed.black,
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  smartNavText: {
    color: colors.bg.elevated,
    fontSize: 13,
    fontWeight: fontWeight.medium,
    marginLeft: spacing._6,
  },
  pulseOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: colors.connection.pulse,
    pointerEvents: "none", // Don't block touch events
    zIndex: 50,
  },
  recenterButton: {
    minWidth: 52,
    minHeight: 52,
    borderRadius: 28,
    backgroundColor: colors.bg.card,
    borderWidth: 1,
    borderColor: colors.border.medium,
    justifyContent: "center",
    alignItems: "center",
    elevation: 4,
    shadowColor: colors.fixed.black,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
});
