name: Test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  test-websocket:
    name: Test WebSocket App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/websocket

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: websocket-test-results
          path: apps/websocket/
          retention-days: 7

  test-filter-processor:
    name: Test Filter Processor App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/filter-processor

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: filter-processor-test-results
          path: apps/filter-processor/
          retention-days: 7

  test-backend:
    name: Test Backend App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backend-test-results
          path: apps/backend/
          retention-days: 7
